services:
  app:
    build: ./
    ports:
      - "8080:8080"
      - "8090:8090"

    depends_on:
      - db
    environment:
      - POSTGRES_DSN="host=db port=6543 user=ozon password=root dbname=ush_db sslmode=disable" #EXAMPLE

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ush_db
      - POSTGRES_USER=ozon    #EXAMPLE
      - POSTGRES_PASSWORD=root   #EXAMPLE
    ports:
      - "6543:5432"

volumes:
  pgdata: {}
