env: local

http_server:
  address: localhost:8080

grpc_server:
  address: localhost:8090

short_links_address: "http://graceful.link.shortener/"

url_generator:
  url_length: 10
  allowed_symbols: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"

db:
  dsn: host=localhost port=6543 user=ozon password=root dbname=ush_db sslmode=disable
